### ISSUE TITLE
not possible to use own OSCAR_INVOICES_INVOICE_MODEL

### ISSUE THREAD

**Issue by jedie** [django-oscar/django-oscar-invoices#15]
The django orm will create migrations if i try to use a own model via OSCAR_INVOICES_INVOICE_MODEL
e.g.:

```
Migrations for 'oscar_invoices':
  /usr/local/lib/python3.6/site-packages/oscar_invoices/migrations/0003_auto_20190312_1322.py
    - Remove field legal_entity from invoice
    - Remove field order from invoice
    - Delete model Invoice
```

**Comment by sasha0** [comment]
Where's your custom invoice model located?

Overall, implicit model customization related to Oscar's limitation to fork and customize apps of external packages - https://github.com/django-oscar/django-oscar/issues/2811.

**Comment by sasha0** [comment]
Works now on latest version and Oscar 2.0. Closing.
