### ISSUE TITLE
raise Error if create_invoice() does nothing...

### ISSUE THREAD

**Issue by jedie** [django-oscar/django-oscar-invoices#16]
If no `LegalEntity` with address exists: `InvoiceCreator().create_invoice(order)` just does nothing.

IMHO it should raise errors ;)

**Comment by sasha0** [comment]
> IMHO it should raise errors ;)

Not sure if that's the best solution, since if invoice creator integrated to the `order_place` signal, it will propagate exception downstream.

So, I added log warning if the legal entity missing within the address.

Thanks for the feedback.
