### ISSUE TITLE
execution error

### ISSUE THREAD

**Issue by gowtham4gs** [django-oscar/django-oscar-invoices#27]
ImportError: cannot import name 'OSCAR_MAIN_TEMPLATE_DIR' from 'oscar' (C:\justin\environments\venv3.7\lib\site-packages\oscar\__init__.py)

**Comment by sasha0** [comment]
I assume this could happen because of incompatibility with Oscar 2.0. Should has been fixed already, since Oscar 2.0 support already brought.
